// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcWSkXtqHzROQvlbPYEO8fPfTGHIMIIdo',
    appId: '1:1009277934311:web:4858a84b0438f5fe53e042',
    messagingSenderId: '1009277934311',
    projectId: 'facturaapp-28d00',
    authDomain: 'facturaapp-28d00.firebaseapp.com',
    storageBucket: 'facturaapp-28d00.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxBLc6L4PYKYyYZpUvwDqjVbyUhJbrX4Y',
    appId: '1:1009277934311:android:27d406a64e032fa153e042',
    messagingSenderId: '1009277934311',
    projectId: 'facturaapp-28d00',
    storageBucket: 'facturaapp-28d00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmkiVsHs2KGlM-_n90PWOfIeiU8Toj1ug',
    appId: '1:1009277934311:ios:bb163ffa3e26d0a453e042',
    messagingSenderId: '1009277934311',
    projectId: 'facturaapp-28d00',
    storageBucket: 'facturaapp-28d00.firebasestorage.app',
    iosBundleId: 'com.example.projet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmkiVsHs2KGlM-_n90PWOfIeiU8Toj1ug',
    appId: '1:1009277934311:ios:bb163ffa3e26d0a453e042',
    messagingSenderId: '1009277934311',
    projectId: 'facturaapp-28d00',
    storageBucket: 'facturaapp-28d00.firebasestorage.app',
    iosBundleId: 'com.example.projet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcWSkXtqHzROQvlbPYEO8fPfTGHIMIIdo',
    appId: '1:1009277934311:web:bebf04a41dad7c5e53e042',
    messagingSenderId: '1009277934311',
    projectId: 'facturaapp-28d00',
    authDomain: 'facturaapp-28d00.firebaseapp.com',
    storageBucket: 'facturaapp-28d00.firebasestorage.app',
  );
}
